plugins:
    - jekyll-remote-theme
    
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Pebble.js Docs
description: Revamped documentation for Pebble.js. Maintained by rebble.io.

color-scheme: auto

favicon: true

navigation:
  - name: Home
    link: ./index.html
  - name: The Basics
    sublist:
      - name: Getting Started
        link: ./getting_started.html
      - name: Images
        link: ./images.html
      - name: Fonts
        link: ./fonts.html
      - name: Using Color
        link: ./using_color.html
      - name: Feature Detection
        link: ./feature_detection.html
  - name: API References
    sublist:
      - name: Require
        link: ./require.html
      - name: Pebble
        link: ./pebble.html
      - name: Local Storage
        link: ./local_storage.html
      - name: HTTP Request
        link: ./http.html
      - name: Window (Browser)
        link: ./window_browser.html
      - name: Clock
        link: ./clock.html
      - name: Platform
        link: ./platform.html
      - name: Feature
        link: ./feature.html
      - name: Settings
        link: ./settings.html
      - name: TimeText
        link: ./timetext.html
  - name: Hardware
    sublist:
      - name: Accelerometer
        link: ./accel.html
      - name: Voice
        link: ./voice.html
      - name: Vibration Motor
        link: ./vibe.html
      - name: Light
        link: ./light.html
  - name: UI Elements
    sublist:
      - name: Window
        link: ./window.html
      - name: Card
        link: ./card.html
      - name: Menu
        link: ./menu.html
      - name: Text
        link: ./text.html
  - name: Graphics
    sublist:
      - name: Image
        link: ./image.html
      - name: Element
        link: ./element.html
      - name: Line
        link: ./line.html
      - name: Circle
        link: ./circle.html
      - name: Radial
        link: ./radial.html
      - name: Rectangle
        link: ./rect.html        
  - name: Miscellaneous
    sublist:
      - name: Timeline
        link: ./timeline.html
      - name: Wakeup
        link: ./wakeup.html
      - name: Vector2
        link: ./vector2.html     
        
